- hosts: localhost
  tasks:
   - name: updates apt
     apt: update_cache=yes

   - name: install aptitude
     apt: pkg=aptitude state=installed

   - name: upgrade apt
     apt: upgrade=full

   - name: install curl
     apt: pkg=curl state=installed

   - name: install pip
     apt: pkg=python-pip state=installed

   - name: ensure docker repo key
     shell: curl -fsSL https://get.docker.com/gpg | apt-key add -

   - name: install docker
     shell: curl -fsSL https://get.docker.com/ | sh

   - name: install latest urllib3 (fix error urllib3.connection.match_hostname = match_hostname)
     pip: name=urllib3 state=latest

   - name: install setuptools
     pip: name=setuptools state=latest

   - name: install pytest
     pip: name=pytest state=latest

   - name: install docker-py
     pip: name=docker-py version=1.7.1

   - name: built and install Containernet (using Mininet installer)
     shell: containernet/util/install.sh
     args:
       chdir: ../../

   - name: install Containernet Python egg etc.
     shell: make develop
     args:
       chdir: ../

   - name: download 'ubuntu' docker image for Containernet example
     shell: docker pull ubuntu:trusty
